name: Protección de merge a rama 'main'.

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  block-non-develop-to-main:
    if: github.base_ref == 'main' && github.head_ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Canelar PR hacia 'main' si no viene desde la rama 'develop'.
        run: |
          echo "❌ El pull request debe provenir desde 'develop' hacia 'main'."
          exit 1