name: Protect Main Branch

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  block-non-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel PR if not from develop
        if: ${{ github.head_ref != 'develop' }}
        run: |
          echo "❌ Un pull request hacia la rama 'main' debe venir desde la rama 'develop'."
          exit 1
